name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_NAME: eatsnearyou  # Set your Azure Web App name

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Specify Node.js version

      # Install dependencies, build, and test the application
      - name: Install, Build, and Test
        run: |
          npm install
          npm run build --if-present
          npm test --if-present

      # Debug: List files in the root and build directories
      - name: List Files
        run: ls -la
      - name: List Build Directory
        run: ls -la ./build

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./build # Update this path if needed
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}

      # Azure logout (optional for security)
      - name: Azure Logout
        run: az logout
